export const DEFAULT_COMPLEXITY_WEIGHTING = 0.25;
export const DEFAULT_WORKLOAD_WEIGHTING = 0.25;
export const DEFAULT_RISK_WEIGHTING = 0.25;
export const DEFAULT_UNCERTAINTY_WEIGHTING = 0.25;
export const DEFAULT_LOWEST_EFFORT = 1;
export const DEFAULT_HIGHEST_EFFORT = 13;
